version: "3.9"

services:
  nextjs:
    image: aplikasi-ga-web:${NODE_ENV}
    container_name: aplikasi-ga-web

    build:
      context: ../..
      dockerfile: docker/Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}

    ports:
      - "${APP_HOST}:${APP_PORT}:${APP_PORT}"

    env_file:
      - ../../.env

    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${APP_PORT}

    networks:
      - ga_network

    restart: unless-stopped

networks:
  ga_network:
    external: true
